apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: surgicsense-hpa
  namespace: healthview-surgicsense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: healthview-surgicsense-backend
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
