apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoexplore-frontend
  namespace: healthview-echoexplore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoexplore-frontend
  template:
    metadata:
      labels:
        app: echoexplore-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: echoexplore-frontend
          image: ghcr.io/curatimexai/echoexplore-frontend:0fe4996ea672eb481ba13bbf9eaa90ecd2c79337
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
