apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nightingale-heartaware
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/curatimeXai/gitops-infra.git
    targetRevision: master
    path: apps/nightingale-heartaware
  destination:
    server: https://kubernetes.default.svc
    namespace: nightingale-heartaware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
