alertmanager:
  alertmanagerSpec:
    alertmanagerConfiguration:
      name: alertmanager-config
    alertmanagerConfigMatcherStrategy:
      type: "None"

kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false