alertmanager:
 alertmanagerSpec: 
   secrets:
      - prometheus-secret 
 config:
   
   receivers:
     - name: "discord-receiver"
       discord_configs:
         - send_resolved: true
        
           webhook_url_file: /etc/alertmanager/secrets/prometheus-secret/DISCORD_WEBHOOK_URL
   route:
     receiver: "discord-receiver"
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 3h
     group_by: ["namespace", "alertname"]
     routes:
       - receiver: "discord-receiver"
         matchers:
           - severity="warning"
         active_time_intervals:
           - business-hours

   time_intervals:
     - name: "business-hours"
       time_intervals:
         - weekdays: ['monday:friday']
           times:
             - start_time: "9:00"
               end_time: "18:00"
           location: "Europe/Frankfurt"
 