loki:
  storage:
    type: s3
    bucketNames: 
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
     endpoint: https://dl46g-private.upcloudobjects.com
     accessKeyId: ${S3_ACCESS_KEY_ID}
     secretAccessKey: ${S3_SECRET_ACCESS_KEY}
     http_config: 
       insecure_skip_verify: false
     s3ForcePathStyle: true
  schema_config:
         configs:
           - from: 2026-06-01
             object_store: s3
             store: tsdb
             schema: v13
             index:
              prefix: loki_index_
              period: 24h
  extraEnvFrom:

    - secretRef:
        name: secret-loki
  
    