apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollutionmap-frontend
  namespace: pollutionmap
  labels:
    app: pollutionmap-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pollutionmap-frontend
  template:
    metadata:
      labels:
        app: pollutionmap-frontend
    spec:
      containers:
        - name: pollutionmap-frontend
          image: ghcr.io/curatimexai/nightingale-pollutionmap-frontend:96e4128eaac1be3e61f4760ce36bd61bcc9c912e
          ports:
            - containerPort: 80
