apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollutionmap-backend
  namespace: pollutionmap
  labels:
    app: pollutionmap-backend
spec:
  selector: 
    matchLabels:
      app: pollutionmap-backend
  template:
    metadata:
      labels:
        app: pollutionmap-backend
    spec:
      imagePullSecrets:
          - name: ghcr-secret
      containers:
        - name: pollutionmap-backend
          image: ghcr.io/curatimexai/nightingale-pollutionmap-backend:4a374aaf647747e76d6aedff30d06fdec692396b
          envFrom:
            - secretRef:
                name: pollutionmap-secret
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
