apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollutionmap-frontend
  namespace: pollutionmap
  labels:
    app: pollutionmap-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pollutionmap-frontend
  template:
    metadata:
      labels:
        app: pollutionmap-frontend
    spec:
      containers:
        - name: pollutionmap-frontend
          image: ghcr.io/curatimexai/nightingale-pollutionmap-frontend:6a0e9a7587ddf3d99e80669ead982f96760c16e3
          ports:
            - containerPort: 80
