apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollutionmap-backend
  namespace: pollutionmap
  labels:
    app: pollutionmap-backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: pollutionmap-backend
  template:
    metadata:
      labels:
        app: pollutionmap-backend
    spec:
      imagePullSecrets:
          - name: ghcr-secret
      containers:
        - name: pollutionmap-backend
          image: ghcr.io/curatimexai/nightingale-pollutionmap-backend:60627b7fadc44cda89720d2b96ff9d17e58388a7
          envFrom:
            - secretRef:
                name: pollutionmap-secret
          ports:
            - containerPort: 3000
