apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollutionmap-backend
  namespace: pollutionmap
  labels:
    app: pollutionmap-backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: pollutionmap-backend
  template:
    metadata:
      labels:
        app: pollutionmap-backend
    spec:
      containers:
        - name: pollutionmap-backend
          image: ghcr.io/curatimexai/nightingale-pollutionmap-backend:3267633c1b91b297ab05e42b5731d66573af6e2e
          envFrom:
            - secretRef:
                name: pollutionmap-secret
          ports:
            - containerPort: 3000
