apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldhealthmap-frontend
  namespace: worldhealthmap
  labels:
    app: worldhealthmap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldhealthmap-frontend
  template:
    metadata:
      labels:
        app: worldhealthmap-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worldhealthmap-frontend
          image: ghcr.io/curatimexai/nightingale-worldhealthmap:8573b0d16ca5837c9b849c4c0f0c81c44ad83e32
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
