apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartaware-frontend
  namespace: nightingale-heartaware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartaware-frontend
  template:
    metadata:
      labels:
        app: heartaware-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: heartaware-frontend
          image: ghcr.io/curatimexai/nightingale-heartaware-frontend:d2a5dc22fd91a0a30ce219aa4b63de03f7083b92
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
