apiVersion: v1
kind: Service
metadata:
  name: echogame-backend-service
  namespace: healthview-echogame
  labels:
    app.kubernetes.io/name: echogame-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: healthview-echogame
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: echogame-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
