apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: causal-modeling-hpa-frontend
  namespace: causal-modeling 
spec:
  scaleTargetRef:
    apiVersion: apps/V1
    kind: Deployment
    name: causal-modeling-frontend
  minReplicas: 1
  maxReplicas: 6
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 75
   - type: Resource
     resource:
       name: memory
       target:
          type: Utilization
          averageUtilization: 75
