apiVersion: v1
kind: Service
metadata:
  name: healthview-surgicsense-demo-frontend
  namespace: healthview-surgicsense-demo
  labels:
    app.kubernetes.io/name: healthview-surgicsense-demo-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: healthview-surgicsense-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: healthview-surgicsense-demo-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
