apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmap-adaptatutor-frontend
  namespace: healthmap-adaptatutor
  labels:
    app.kubernetes.io/name: healthmap-adaptatutor-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: healthmap-adaptatutor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: healthmap-adaptatutor-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: healthmap-adaptatutor-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: healthmap-adaptatutor
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/curatimexai/healthmap-adaptatutor-frontend:3936e49b94c170e102622ec505278e167b540080
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
