apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecgprediction-frontend
  namespace: ecgprediction
  labels:
    app: ecgprediction-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecgprediction-frontend
  template:
    metadata:
      labels:
        app: ecgprediction-frontend
    spec:
      containers:
        - name: ecgprediction-frontend
          image: ghcr.io/curatimexai/nightingale-ecgprediction-frontend:f5e9d55125ddee0d560897866f03d6cf8604315b
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecgprediction-secret
