apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecgprediction-frontend
  namespace: ecgprediction
  labels:
    app: ecgprediction-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ecgprediction-frontend
  template:
    metadata:
      labels:
        app: ecgprediction-frontend
    spec:
      
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ecgprediction-frontend
          image: ghcr.io/curatimexai/nightingale-ecgprediction-frontend:b442e1cc301c6e85532c56427dbfa77caa2159fe
          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          

