apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecgprediction-backend
  namespace: ecgprediction
  labels:
    app: ecgprediction-backend
spec:
  revisionHistoryLimit: 2
  
  selector:
    matchLabels:
      app: ecgprediction-backend
  template:
    metadata:
      labels:
        app: ecgprediction-backend
    spec:
      
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ecgprediction-backend
          image: ghcr.io/curatimexai/nightingale-ecgprediction-backend:122b1910e20de49eaf66614a70c7d12028335faa
          envFrom:
            - secretRef:
                name: ecgprediction-secret
          ports:
            - containerPort: 8000
          resources: 
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          startupProbe:     
            tcpSocket:
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000      
            initialDelaySeconds: 30
            periodSeconds: 30


