apiVersion: v1
kind: Service
metadata:
  name: healthview-segmentation3d-frontend
  namespace: healthview-segmentation3d
  labels:
    app.kubernetes.io/name: healthview-segmentation3d-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: healthview-segmentation3d-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
