apiVersion: v1
kind: ConfigMap
metadata:
  name: healthview-segmentation3d-frontend-config
  namespace: healthview-segmentation3d
  labels:
    app.kubernetes.io/name: healthview-segmentation3d-frontend
data:
  config.js: |
    const API_BASE_URL = "https://segmentation-api.nightingaleheart.com";
    const S3_MODELS_URL = "https://healthview-segmentation3d-models-prod.s3.eu-central-1.amazonaws.com/models";
