apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: heartsaying-network-policy
  namespace: healthmap-heart-sayings
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: healthmap-heart-sayings
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-ingress
          
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
       - IpBlock:
            cidr: 10.0.0.0/24
      ports:
         - protocol: TCP
           port: 11569
              