apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-frontend
  namespace: ai-whatif
  labels:
    app: aiwhatif-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiwhatif-frontend
  template:
    metadata:
      labels:
        app: aiwhatif-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-frontend
          image: ghcr.io/curatimexai/nightingale-aiwhatif-frontend:d895bbc3d8cf6a71a889c053385d977faaa56720
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
