apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aiwhatif-backend
  template:
    metadata:
      labels:
        app: aiwhatif-backend
    spec:
      containers:
        - name: aiwhatif-backend
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend:4512b00d510608562d162854a376fc806c581e25
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 9000
