apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend-py
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend-py
spec:
  
  selector:
    matchLabels:
      app: aiwhatif-backend-py
  template:
    metadata:
      labels:
        app: aiwhatif-backend-py
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-backend-py
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend-python:466527a22a1bdf84c3254a606f58ae5c4d3862b9
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
