apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend-py
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend-py
spec:
  
  selector:
    matchLabels:
      app: aiwhatif-backend-py
  template:
    metadata:
      labels:
        app: aiwhatif-backend-py
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-backend-py
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend-python:ea664fd3e034ab830e30b38ce2815a4c39d4bcd0
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:  
              path: /healthy
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /healthy
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthy
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
