apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend-r
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend-r
spec:
  
  selector:
    matchLabels:
      app: aiwhatif-backend-r
  template:
    metadata:
      labels:
        app: aiwhatif-backend-r
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-backend-r
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend-r:7494c44050d1af44431f616f6111b7e0b3676a0a
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 9000
          
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
          startupProbe:
            tcpSocket:
              port: 9000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 4Gi
        
