apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend-r
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend-r
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aiwhatif-backend-r
  template:
    metadata:
      labels:
        app: aiwhatif-backend-r
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-backend-r
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend-r:b388a7a2f6f22afd8f1c51526d31282a82a8ac8c
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 9000
