apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-backend-py
  namespace: ai-whatif
  labels:
    app: aiwhatif-backend-py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aiwhatif-backend-py
  template:
    metadata:
      labels:
        app: aiwhatif-backend-py
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-backend-py
          image: ghcr.io/curatimexai/nightingale-aiwhatif-backend-python:9c251b951b9905898edf05285ad3d95676f74f8c
          envFrom:
            - secretRef:
                name: aiwhatif-secret
          ports:
            - containerPort: 8000
