apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwhatif-frontend
  namespace: ai-whatif
  labels:
    app: aiwhatif-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiwhatif-frontend
  template:
    metadata:
      labels:
        app: aiwhatif-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aiwhatif-frontend
          image: ghcr.io/curatimexai/nightingale-aiwhatif-frontend:976bb92868eb9916f279894fa30ac46393839a59
          ports:
            - containerPort: 80
