apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
 name: "aiwhatif-backend-network-policy"
 namespace: ai-whatif
spec:
 endpointSelector:
   matchLabels:
     type: backend
 egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
         dns:
           - matchName: "https://8ps1i.upcloudobjects.com/aiwhatif"
  - toFQDNs:
     - matchName: "8ps1i-private.upcloudobjects.comhttps://8ps1i.upcloudobjects.com/aiwhatif" 
    toPorts:
     - ports:
       - port: "443"
         protocol: TCP

     
  