apiVersion: v1
kind: Service
metadata: 
  name: aiwhatif-backend-service
  namespace: ai-whatif
spec:
  selector:
    app: aiwhatif-backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
 
