apiVersion: v1
kind: Service
metadata: 
  name: aiwhatif-frontend-service
  namespace: ai-whatif
spec:
  selector:
    app: aiwhatif-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
